language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpoppler-cpp-dev unpaper tesseract-ocr imagemagick ghostscript

install:
  - pip install --upgrade pipenv
  - pipenv install --system --dev

script:
  - cd src/
  - pipenv run pytest --cov
  - pipenv run pycodestyle

after_success:
  - pipenv run coveralls
