apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Production environment: HA settings, resource limits
# patches:
#   - path: patches/replica-count.yaml
#   - path: patches/env-prod.yaml
#   - path: patches/resources.yaml
