blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Questions and Help
    url: https://github.com/paperless-ngx/paperless-ngx/discussions
    about: General questions or support for using Paperless-ngx.
  - name: ðŸ’¬ Chat
    url: https://matrix.to/#/#paperlessngx:matrix.org
    about: Want to discuss Paperless-ngx with others? Check out our chat.
  - name: ðŸš€ Feature Request
    url: https://github.com/paperless-ngx/paperless-ngx/discussions/new?category=feature-requests
    about: Remember to search for existing feature requests and "up-vote" those that you like.
