# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), MariaDB is used as the database server.

version: "3.4"
services:
  broker:
    extends:
      file: docker-compose.lib.yml
      service: redis

  db:
    extends:
      file: docker-compose.lib.yml
      service: mariadb

  paperless:
    extends:
      file: docker-compose.lib.yml
      service: paperless
    depends_on:
      - db
      - broker
    environment:
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_DBPORT: 3306

volumes:
  data:
  media:
  dbdata:
  redisdata:
