# Files containing the definition of all services used in the
# Docker Compose file where we have coherent compositing.

version: "3.4"
services:
  redis:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ${REDIS_DATA_VOLUME}:/data

  postgres:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - ${POSGRES_DATA_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=paperless
      - POSTGRES_USER=paperless
      - POSTGRES_PASSWORD=paperless
      - POSTGRES_INITDB_ARGS
      - POSTGRES_INITDB_WALDIR
      - POSTGRES_HOST_AUTH_METHOD
      - PGDATA
      # To be able to use psql dirrectly
      - PGDATABASE=paperless
      - PGUSER=paperless
      - PGPASSWORD=paperless
      - PGHOST=localhost

  mariadb:
    image: docker.io/library/mariadb:10
    restart: unless-stopped
    volumes:
      - ${MARIADB_DATA_VOLUME}:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=paperless
      - MARIADB_USER=paperless
      - MARIADB_PASSWORD=paperless
      - MARIADB_ROOT_PASSWORD=paperless
      - MARIADB_ROOT_PASSWORD_HASH
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
      - MARIADB_RANDOM_ROOT_PASSWORD
      - MARIADB_ROOT_HOST
      - MARIADB_MYSQL_LOCALHOST_USER
      - MARIADB_MYSQL_LOCALHOST_GRANTS
      - MARIADB_PASSWORD_HASH
      - MARIADB_INITDB_SKIP_TZINFO
      - MARIADB_AUTO_UPGRADE
      - MARIADB_DISABLE_UPGRADE_BACKUP

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    ports:
      - ${PAPERLESS_PORT}:${PAPERLESS_INNER_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${PAPERLESS_DATA_VOLUME}:/usr/src/paperless/data
      - ${PAPERLESS_MEDIA_VOLUME}:/usr/src/paperless/media
      - ${PAPERLESS_EXPORT_VOLUME}:/usr/src/paperless/export
      - ${PAPERLESS_CONSUME_VOLUME}:/usr/src/paperless/consume
    environment:
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_DBENGINE
      - PAPERLESS_DBHOST
      - PAPERLESS_DBPORT
      - PAPERLESS_DBNAME
      - PAPERLESS_DBUSER
      - PAPERLESS_DBPASS
      - PAPERLESS_DBSSLMODE
      - PAPERLESS_DB_TIMEOUT
      - PAPERLESS_CONSUMPTION_DIR
      - PAPERLESS_DATA_DIR
      - PAPERLESS_TRASH_DIR
      - PAPERLESS_MEDIA_ROOT
      - PAPERLESS_STATICDIR
      - PAPERLESS_FILENAME_FORMAT
      - PAPERLESS_FILENAME_FORMAT_REMOVE_NONE
      - PAPERLESS_LOGGING_DIR
      - PAPERLESS_NLTK_DIR
      - PAPERLESS_LOGROTATE_MAX_SIZE
      - PAPERLESS_LOGROTATE_MAX_BACKUPS
      - PAPERLESS_SECRET_KEY
      - PAPERLESS_URL
      - PAPERLESS_CSRF_TRUSTED_ORIGINS
      - PAPERLESS_ALLOWED_HOSTS
      - PAPERLESS_CORS_ALLOWED_HOSTS
      - PAPERLESS_FORCE_SCRIPT_NAME
      - PAPERLESS_STATIC_URL
      - PAPERLESS_AUTO_LOGIN_USERNAME
      - PAPERLESS_ADMIN_USER
      - PAPERLESS_ADMIN_MAIL
      - PAPERLESS_ADMIN_PASSWORD
      - PAPERLESS_COOKIE_PREFIX
      - PAPERLESS_ENABLE_HTTP_REMOTE_USER
      - PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME
      - PAPERLESS_LOGOUT_REDIRECT_URL
      - PAPERLESS_OCR_LANGUAGE
      - PAPERLESS_OCR_MODE
      - PAPERLESS_OCR_CLEAN
      - PAPERLESS_OCR_DESKEW
      - PAPERLESS_OCR_ROTATE_PAGES
      - PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD
      - PAPERLESS_OCR_OUTPUT_TYPE
      - PAPERLESS_OCR_PAGES
      - PAPERLESS_OCR_IMAGE_DPI
      - PAPERLESS_OCR_MAX_IMAGE_PIXELS
      - PAPERLESS_OCR_USER_ARGS
      - PAPERLESS_TIKA_ENABLED
      - PAPERLESS_TIKA_ENDPOINT
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT
      - PAPERLESS_TASK_WORKERS
      - PAPERLESS_THREADS_PER_WORKER
      - PAPERLESS_WORKER_TIMEOUT
      - PAPERLESS_WORKER_RETRY
      - PAPERLESS_TIME_ZONE
      - PAPERLESS_ENABLE_NLTK
      - PAPERLESS_EMAIL_TASK_CRON
      - PAPERLESS_TRAIN_TASK_CRON
      - PAPERLESS_INDEX_TASK_CRON
      - PAPERLESS_SANITY_TASK_CRON
      - PAPERLESS_CONSUMER_POLLING
      - PAPERLESS_CONSUMER_POLLING_RETRY_COUNT
      - PAPERLESS_CONSUMER_POLLING_DELAY
      - PAPERLESS_CONSUMER_INOTIFY_DELAY
      - PAPERLESS_CONSUMER_DELETE_DUPLICATES
      - PAPERLESS_CONSUMER_RECURSIVE
      - PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS
      - PAPERLESS_CONSUMER_ENABLE_BARCODES
      - PAPERLESS_CONSUMER_BARCODE_TIFF_SUPPORT
      - PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE
      - PAPERLESS_CONVERT_MEMORY_LIMIT
      - PAPERLESS_CONVERT_TMPDIR
      - PAPERLESS_POST_CONSUME_SCRIPT
      - PAPERLESS_FILENAME_DATE_ORDER
      - PAPERLESS_NUMBER_OF_SUGGESTED_DATES
      - PAPERLESS_THUMBNAIL_FONT_NAME
      - PAPERLESS_IGNORE_DATES
      - PAPERLESS_DATE_ORDER
      - PAPERLESS_CONSUMER_IGNORE_PATTERNS
      - PAPERLESS_CONVERT_BINARY
      - PAPERLESS_GS_BINARY
      - PAPERLESS_WEBSERVER_WORKERS
      - PAPERLESS_BIND_ADDR
      - PAPERLESS_PORT
      - PAPERLESS_OCR_LANGUAGES
      - PAPERLESS_ENABLE_FLOWER
      - PAPERLESS_ENABLE_UPDATE_CHECK
      - USERMAP_UID
      - USERMAP_GID

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
