# SQLite is used as the database. The SQLite file is stored in the data volume.
#
# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.

version: "3.4"
services:
  broker:
    extends:
      file: docker-compose.lib.yml
      service: redis

  paperless:
    extends:
      file: docker-compose.lib.yml
      service: paperless
    depends_on:
      - broker
      - gotenberg
      - tika
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    extends:
      file: docker-compose.lib.yml
      service: gotenberg

  tika:
    extends:
      file: docker-compose.lib.yml
      service: tika

volumes:
  data:
  media:
  redisdata:
