# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), MariaDB is used as the database server.
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.

version: "3.4"
services:
  broker:
    extends:
      file: docker-compose.lib.yaml
      service: redis

  db:
    extends:
      file: docker-compose.lib.yaml
      service: mariadb

  paperless:
    extends:
      file: docker-compose.lib.yaml
      service: paperless
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    environment:
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_DBPORT: 3306
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    extends:
      file: docker-compose.lib.yaml
      service: gotenberg

  tika:
    extends:
      file: docker-compose.lib.yaml
      service: tika

volumes:
  data:
  media:
  dbdata:
  redisdata:
