apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace is derived from PROJECT_NAME in .env
namespace: paless

resources:
  - namespace.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - redis-statefulset.yaml
  - redis-service.yaml
  - configmap.yaml
  - paless-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
