apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  labels:
    app: paperless
data:
  rclone.conf: |
    [minio]
    type = s3
    provider = Minio
    endpoint = http://minio:9000
    env_auth = true
    acl = private
