apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paless-web
  labels:
    app: paless
    component: web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  rules:
    - host: paless.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paless-web
                port:
                  number: 8000
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paless-web
                port:
                  number: 8000
