apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Dev environment: single replica, debug logging
patches:
  - path: paless-secret-patch.yaml
    target:
      kind: Secret
      name: paless-secret
#   - path: patches/replica-count.yaml
#   - path: patches/env-dev.yaml
