---
name: Ansible Role

on: [push, pull_request]

jobs:
  # https://molecule.readthedocs.io/en/latest/ci.html#github-actions
  test:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && contains(github.ref, 'refs/heads/'))
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install molecule[ansible,docker]
          ansible --version
          docker --version
          molecule --version
          python --version
      - name: Test with molecule
        run: |
          cd ansible
          molecule test
        working-directory: "${{ github.repository }}"
  # https://galaxy.ansible.com/docs/contributing/importing.html
  release:
    runs-on: ubuntu-latest
    needs:
      - test
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
    if: contains(github.ref, 'refs/tags/')
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade ansible-base
          ansible --version
          python --version
      - name: Trigger a new import on Galaxy
        run: |
          cd ansible
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
        working-directory: "${{ github.repository }}"
